feat: api inference for gan and diffusion
chore: gitignore logs generated during inference

chore: black formatting

feat: enable inference synchronous requests

fix: mp RuntimeError when starting uvicorn server

Pass raised exception when starting server with `./server/run.sh` command.

```sh
  File "/joliGEN/server/joligen_api.py", line 13, in <module>
    mp.set_start_method("spawn")
  File "/usr/lib/python3.10/multiprocessing/context.py", line 247, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

fix: modify `--name` argument on Inference options

`--name` argument was missing in InferenceGANOptions and has been
redefined as the inference process name in InferenceDiffusionOptions.

fix(scripts): bdd100k bboxes coordinates in the right order

doc: options auto update

fix: not force reloading dinov2 models

doc: options auto update

Update test_api_predict_gan.py to include debug print

Update test_api_predict_gan.py

remove newlines to pass black check

fix: save_config in test_run_nosemantic for later use in test_api

fix: add model_type in /predict predict_options

fix: use abspath in test_api_

test: save_config flag for util/parser.get_opt

fix: black format

fix: save_config extract in utils/parser.get_opt

docs: curl commands for inference on api server

fix: save_config=True on all tests

fix: fixture to create missing model during test

fix: remove gpuid

fix: image size during diffusion inference

fix: update pluggy lib

fix: use $TARGET_MASK_SEM_DIR as dataroot

fix: checkpoint_dir path

debug: print path info

fix: move test cleanup to run_test endfile

fix: find checkpoint in `dir_model/name`