fix: mp RuntimeError when starting uvicorn server
Pass raised exception when starting server with `./server/run.sh` command.

```sh
  File "/joliGEN/server/joligen_api.py", line 13, in <module>
    mp.set_start_method("spawn")
  File "/usr/lib/python3.10/multiprocessing/context.py", line 247, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```